name: firebase_timeline_repository
description: "A new Flutter package project."
version: 7.0.0
publish_to: none

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  timeline_repository_interface:
    git:
      url: https://github.com/Iconica-Development/flutter_timeline
      path: packages/timeline_repository_interface
      ref: 7.0.0

  rxdart: any
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.2
  collection: ^1.18.0

dev_dependencies:
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 7.0.0
