# SPDX-FileCopyrightText: 2023 Iconica
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: flutter_timeline_firebase
description: Implementation of the Flutter Timeline interface for Firebase.
version: 4.1.1
publish_to: https://forgejo.internal.iconica.nl/api/packages/internal/pub

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.6
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.5
  uuid: ^4.2.1

  flutter_timeline_interface:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^4.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 6.0.0

flutter:

