name: example
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_timeline:
    git:
      url: https://github.com/Iconica-Development/flutter_timeline
      ref: 6.0.0
      path: packages/flutter_timeline
  intl: 0.19.0
dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Merriweather
      fonts:
        - asset: fonts/Merriweather-Regular.ttf
    - family: Avenir
      fonts:
        - asset: fonts/Avenir-Regular.ttf
